version: '3.9'
networks:
  server-network:
    driver: bridge
secrets:
  DB_USERNAME:
    file: ./secrets/DB_USERNAME.secret.txt
  DB_PASSWORD:
    file: ./secrets/DB_PASSWORD.secret.txt
  DB_HOST:
    file: ./secrets/DB_HOST.secret.txt
  DB_NAME:
    file: ./secrets/DB_NAME.secret.txt
volumes:
  pictures:
services:
  app:
    container_name: redes2-docker-front
    image: redes2-docker-front:latest
    build: ../redes2-docker-front/
    restart: unless-stopped
    ports:
      - 3001:80
    networks:
      - server-network
    volumes:
      - pictures:/usr/share/nginx/html/images
  server:
    container_name: redes2-docker-back
    image: redes2-docker-back:latest
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - server-network
    secrets:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
    env_file:
      - .production.env
  db:
    image: mongo:latest
    container_name: redes2-docker-db
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - server-network
    secrets:
      - DB_USERNAME
      - DB_PASSWORD
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/DB_PASSWORD
